[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# 정적 파일 경로 제외
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
